port = 8080
port = ${?ORDER_SERVICE_PORT}

metrics-port = 9090
metrics-port = ${?ORDER_SERVICE_METRICS_PORT}

service-name = "order-service"
service-name = ${?ORDER_SERVICE_NAME}

postgres {
  host = "localhost"
  host = ${?POSTGRES_HOST}
  port = 5432
  port = ${?POSTGRES_PORT}
  database = "orders"
  database = ${?POSTGRES_DB}
  user = "orders"
  user = ${?POSTGRES_USER}
  password = "orders"
  password = ${?POSTGRES_PASSWORD}
}
