#!/usr/bin/env bash
set -euo pipefail

# Generates a new service from this repo's giter8 template, optionally
# extends it with extra domain fields via tools/codegen, creates a public
# GitHub repo under the caller's account, pushes the service, wires up
# GitHub Actions CI credentials, and waits for that first CI run to go
# green - this project's answer to service-generator's Jenkins pipeline.
#
# Usage:
#   ./scripts/generate-and-publish-service.sh --domain-name <name> \
#     [--package <package>] [--field-spec <path>] [--repo-name <name>]
#
# Requires: gh (authenticated), sbt, Docker (for the generated service's
# Postgres-backed tests).

usage() {
  cat <<'USAGE'
Usage: generate-and-publish-service.sh --domain-name <name> [options]

Required:
  --domain-name <name>   Lowercase, singular domain name (e.g. "widget").

Options:
  --package <package>    Scala package for the generated service.
                          Defaults to giter8's own default ($domain_name$service).
  --field-spec <path>    Path to a field-spec YAML file (see tools/codegen's README
                          section) to apply via the field-codegen tool before pushing.
  --repo-name <name>     GitHub repo name. Defaults to "<domain-name>-service".
  -h, --help             Show this help and exit.
USAGE
}

DOMAIN_NAME=""
PACKAGE=""
FIELD_SPEC=""
REPO_NAME=""

while [ $# -gt 0 ]; do
  case "$1" in
    --domain-name)
      DOMAIN_NAME="$2"
      shift 2
      ;;
    --package)
      PACKAGE="$2"
      shift 2
      ;;
    --field-spec)
      FIELD_SPEC="$2"
      shift 2
      ;;
    --repo-name)
      REPO_NAME="$2"
      shift 2
      ;;
    -h | --help)
      usage
      exit 0
      ;;
    *)
      echo "Unknown argument: $1" >&2
      usage >&2
      exit 1
      ;;
  esac
done

if [ -z "$DOMAIN_NAME" ]; then
  echo "Error: --domain-name is required." >&2
  usage >&2
  exit 1
fi

if [ -n "$FIELD_SPEC" ]; then
  if [ ! -f "$FIELD_SPEC" ]; then
    echo "Error: --field-spec file not found: $FIELD_SPEC" >&2
    exit 1
  fi
  # Resolve to an absolute path before any `cd` below.
  FIELD_SPEC="$(cd "$(dirname "$FIELD_SPEC")" && pwd)/$(basename "$FIELD_SPEC")"
fi

if [ -z "$REPO_NAME" ]; then
  REPO_NAME="${DOMAIN_NAME}-service"
fi

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
CODEGEN_DIR="$ROOT_DIR/tools/codegen"

echo "Domain name: $DOMAIN_NAME"
echo "Package:     ${PACKAGE:-<default>}"
echo "Field spec:  ${FIELD_SPEC:-<none>}"
echo "Repo name:   $REPO_NAME"

WORK_DIR="$(mktemp -d -t generate-and-publish-service)"
cleanup() {
  rm -rf "$WORK_DIR"
}
trap cleanup EXIT

# A throwaway sbt project used only to run giter8's launcher library -
# project-local, not a global plugin, so nothing about the caller's sbt
# environment changes. Same pattern as scripts/verify-g8-template.sh.
LAUNCHER_DIR="$WORK_DIR/g8-launcher"
mkdir -p "$LAUNCHER_DIR/project"
echo "sbt.version=1.13.0" >"$LAUNCHER_DIR/project/build.properties"
echo 'libraryDependencies += "org.foundweekends.giter8" %% "giter8-launcher" % "0.18.0"' \
  >"$LAUNCHER_DIR/build.sbt"

GEN_DIR="$WORK_DIR/$REPO_NAME"

echo
echo "1. Generating '$DOMAIN_NAME' service from this repo's template..."
GEN_ARGS=(--domain_name="$DOMAIN_NAME")
if [ -n "$PACKAGE" ]; then
  GEN_ARGS+=(--package="$PACKAGE")
fi
(cd "$LAUNCHER_DIR" && sbt -batch "runMain giter8.LauncherMain file://${ROOT_DIR} ${GEN_ARGS[*]} -o ${GEN_DIR}") \
  >"$WORK_DIR/generate.log" 2>&1 || {
  echo "   FAIL: generation failed" >&2
  tail -60 "$WORK_DIR/generate.log" >&2
  exit 1
}
echo "   OK: generated at $GEN_DIR"

if [ -n "$FIELD_SPEC" ]; then
  echo
  echo "2. Applying field-spec via the field-codegen tool..."
  (cd "$CODEGEN_DIR" && sbt -batch "runMain codegen.Main ${GEN_DIR} ${FIELD_SPEC}") \
    >"$WORK_DIR/codegen.log" 2>&1 || {
    echo "   FAIL: field-codegen tool failed" >&2
    tail -80 "$WORK_DIR/codegen.log" >&2
    exit 1
  }
  echo "   OK: field spec applied"
fi

STEP=2
if [ -n "$FIELD_SPEC" ]; then
  STEP=3
fi

echo
echo "$STEP. Checking whether $REPO_NAME already exists on GitHub..."
OWNER="$(gh api user --jq .login)"
if gh repo view "$OWNER/$REPO_NAME" >/dev/null 2>&1; then
  echo "   FAIL: $OWNER/$REPO_NAME already exists - not overwriting." >&2
  exit 1
fi
echo "   OK: $OWNER/$REPO_NAME is available"
STEP=$((STEP + 1))

echo
echo "$STEP. Committing the generated service locally..."
(
  cd "$GEN_DIR"
  git init -q
  git add -A
  git -c user.name="pure-service-generator" -c user.email="noreply@localhost" \
    commit -q -m "Initial commit: generated by pure-service-generator"
  git branch -M main
)
echo "   OK: committed on branch 'main'"
STEP=$((STEP + 1))

echo
echo "$STEP. Creating public repo $OWNER/$REPO_NAME and wiring it as 'origin'..."
gh repo create "$OWNER/$REPO_NAME" --public --source="$GEN_DIR" --remote=origin \
  >"$WORK_DIR/repo-create.log" 2>&1 || {
  echo "   FAIL: gh repo create failed" >&2
  cat "$WORK_DIR/repo-create.log" >&2
  exit 1
}
echo "   OK: created https://github.com/$OWNER/$REPO_NAME"
STEP=$((STEP + 1))

echo
echo "$STEP. Setting GH_PACKAGES_TOKEN CI secret (before the first push, so CI can resolve"
echo "   GitHub Packages)..."
gh secret set GH_PACKAGES_TOKEN --repo "$OWNER/$REPO_NAME" --body "$(gh auth token)" \
  >"$WORK_DIR/secret-set.log" 2>&1 || {
  echo "   FAIL: gh secret set failed" >&2
  cat "$WORK_DIR/secret-set.log" >&2
  exit 1
}
echo "   OK: secret set"
STEP=$((STEP + 1))

echo
echo "$STEP. Pushing to $OWNER/$REPO_NAME..."
(cd "$GEN_DIR" && git push -u origin main) >"$WORK_DIR/push.log" 2>&1 || {
  echo "   FAIL: git push failed" >&2
  cat "$WORK_DIR/push.log" >&2
  exit 1
}
echo "   OK: pushed"
STEP=$((STEP + 1))

echo
echo "$STEP. Waiting for the triggered GitHub Actions run to complete..."
PUSHED_SHA="$(cd "$GEN_DIR" && git rev-parse HEAD)"

RUN_ID=""
for _ in $(seq 1 30); do
  RUN_ID="$(gh run list --repo "$OWNER/$REPO_NAME" --json databaseId,headSha \
    --jq ".[] | select(.headSha == \"$PUSHED_SHA\") | .databaseId" 2>/dev/null | head -1)"
  if [ -n "$RUN_ID" ]; then
    break
  fi
  sleep 2
done

if [ -z "$RUN_ID" ]; then
  echo "   FAIL: no GitHub Actions run appeared for commit $PUSHED_SHA within the timeout." >&2
  exit 1
fi

echo "   Found run $RUN_ID, watching..."
if gh run watch "$RUN_ID" --repo "$OWNER/$REPO_NAME" --exit-status; then
  echo "   OK: CI run $RUN_ID passed"
else
  echo "   FAIL: CI run $RUN_ID did not pass - see https://github.com/$OWNER/$REPO_NAME/actions/runs/$RUN_ID" >&2
  exit 1
fi

echo
echo "Done: https://github.com/$OWNER/$REPO_NAME"
